spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://ai-postgres:5432/ai_business
    username: aiuser
    password: aipass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9000